using System.Collections.Generic;
using Tripper.XNAMath;

namespace Styx.Logic.Pathing.FlightorNavigation;

// Generated by Tools/EvidenceAudit/aerial_settlements_335.py.
// Original client build12340 faction masks plus pinned TDB335.25101.
// Bounds contain an explicit 80-yard planning margin, not a server aggro guarantee.
internal static class AerialSettlementData
{
    internal readonly record struct Region(uint Map, WoWFactionGroup Owner, float MinX, float MinY, float MaxX, float MaxY, string Id);
    internal static readonly Region[] Regions = new[]
    {
        new Region(530U, WoWFactionGroup.Alliance, -3140.14f, 3759.48f, -2792.9f, 4240.95f, "530-Alliance-39631"),
        new Region(530U, WoWFactionGroup.Alliance, -4370.35f, -12038.2f, -3541.43f, -11384.7f, "530-Alliance-57750"),
        new Region(530U, WoWFactionGroup.Alliance, -952.166f, 2410.89f, -492.22f, 2992.03f, "530-Alliance-57880"),
        new Region(530U, WoWFactionGroup.Alliance, -2318.78f, -12163.6f, -1730.56f, -11682.8f, "530-Alliance-63162"),
        new Region(530U, WoWFactionGroup.Alliance, 115.944f, 5858.95f, 432.731f, 6198.58f, "530-Alliance-65519"),
        new Region(530U, WoWFactionGroup.Alliance, -5.9365f, 4070.55f, 335.531f, 4466.27f, "530-Alliance-67055"),
        new Region(530U, WoWFactionGroup.Alliance, -2876.6f, 7056.64f, -2408.01f, 7544.99f, "530-Alliance-67057"),
        new Region(530U, WoWFactionGroup.Alliance, 846.915f, 7230.59f, 1136.38f, 7539.85f, "530-Alliance-67881"),
        new Region(530U, WoWFactionGroup.Alliance, 1843.72f, 6630.1f, 2267.88f, 6986.18f, "530-Alliance-67959"),
        new Region(530U, WoWFactionGroup.Alliance, -4203.41f, 1839.68f, -3701.53f, 2405.27f, "530-Alliance-67961"),
        new Region(530U, WoWFactionGroup.Alliance, 1755.53f, 5433.13f, 2040.02f, 5683.07f, "530-Alliance-74141"),
        new Region(530U, WoWFactionGroup.Alliance, -4409.21f, -12617.8f, -4049.43f, -12229.5f, "530-Alliance-82948"),
        new Region(530U, WoWFactionGroup.Alliance, 193.556f, 1359.38f, 402.826f, 1578.06f, "530-Alliance-96986"),
        new Region(530U, WoWFactionGroup.Horde, 8591.61f, -6887.89f, 8835.61f, -6542.22f, "530-Horde-55353"),
        new Region(530U, WoWFactionGroup.Horde, 9170.39f, -7658.02f, 10098.3f, -6605.43f, "530-Horde-55372"),
        new Region(530U, WoWFactionGroup.Horde, -54.2085f, 2455.33f, 377.892f, 2930.29f, "530-Horde-57559"),
        new Region(530U, WoWFactionGroup.Horde, 92.291f, 7613.15f, 514.477f, 8044.57f, "530-Horde-65513"),
        new Region(530U, WoWFactionGroup.Horde, -2786.72f, 4193.74f, -2465.67f, 4566.83f, "530-Horde-67162"),
        new Region(530U, WoWFactionGroup.Horde, -1568.33f, 6860.27f, -1085.59f, 7480.36f, "530-Horde-67163"),
        new Region(530U, WoWFactionGroup.Horde, -786.67f, 3988.19f, -488.976f, 4272.39f, "530-Horde-67878"),
        new Region(530U, WoWFactionGroup.Horde, 2173.98f, 5835.76f, 2572.92f, 6214.3f, "530-Horde-68082"),
        new Region(530U, WoWFactionGroup.Horde, -3334.25f, 2300.82f, -2823f, 2833.93f, "530-Horde-68902"),
        new Region(530U, WoWFactionGroup.Horde, -1426.72f, 2264.15f, -1231.05f, 2477.58f, "530-Horde-69965"),
        new Region(530U, WoWFactionGroup.Horde, -4.7063f, 5059.28f, 212.889f, 5341.42f, "530-Horde-73242"),
        new Region(530U, WoWFactionGroup.Horde, 1924.48f, 4595.43f, 2333f, 4916.56f, "530-Horde-74114"),
        new Region(530U, WoWFactionGroup.Horde, 7403.42f, -6985.62f, 7767.18f, -6646.99f, "530-Horde-81714"),
        new Region(571U, WoWFactionGroup.Alliance, 3359.4f, 1859.77f, 3650.67f, 2164.88f, "571-Alliance-95646"),
        new Region(571U, WoWFactionGroup.Alliance, 4402.69f, -4341.83f, 4688.41f, -4041.77f, "571-Alliance-97240"),
        new Region(571U, WoWFactionGroup.Alliance, 1215.85f, -3548.76f, 1582.67f, -3007.78f, "571-Alliance-100698"),
        new Region(571U, WoWFactionGroup.Alliance, 6513.36f, -567.759f, 6808.47f, 49.64f, "571-Alliance-100834"),
        new Region(571U, WoWFactionGroup.Alliance, 4949.87f, -793.278f, 5216.13f, -414.455f, "571-Alliance-101940"),
        new Region(571U, WoWFactionGroup.Alliance, 1991.78f, 5037.86f, 2572.51f, 5602.85f, "571-Alliance-107742"),
        new Region(571U, WoWFactionGroup.Alliance, 439.569f, -5186.95f, 915.849f, -4805.26f, "571-Alliance-112850"),
        new Region(571U, WoWFactionGroup.Alliance, 3963.77f, 5146.44f, 4316.15f, 5496.71f, "571-Alliance-117745"),
        new Region(571U, WoWFactionGroup.Alliance, 2261.15f, -5289.74f, 2691.5f, -4823.28f, "571-Alliance-120340"),
        new Region(571U, WoWFactionGroup.Alliance, 3455.7f, -1009.996f, 4017.69f, -589.47f, "571-Alliance-131254"),
        new Region(571U, WoWFactionGroup.Alliance, 4490.17f, 1330.71f, 4686.09f, 1559.3f, "571-Alliance-133901"),
        new Region(571U, WoWFactionGroup.Horde, 7754.25f, -892.057f, 7957.79f, -651.14f, "571-Horde-88168"),
        new Region(571U, WoWFactionGroup.Horde, 2517.28f, -4479.41f, 2801.46f, -4222.24f, "571-Horde-96494"),
        new Region(571U, WoWFactionGroup.Horde, 7679.75f, -3050.85f, 7912.13f, -2723.58f, "571-Horde-97716"),
        new Region(571U, WoWFactionGroup.Horde, 1553.86f, -6342.24f, 2104.24f, -5936.08f, "571-Horde-98071"),
        new Region(571U, WoWFactionGroup.Horde, 3748.75f, -4649.81f, 3961.99f, -4231f, "571-Horde-100936"),
        new Region(571U, WoWFactionGroup.Horde, 5452.98f, -837.188f, 5706.6f, -533.882f, "571-Horde-101720"),
        new Region(571U, WoWFactionGroup.Horde, 3266.64f, 3956.05f, 3642.16f, 4308.28f, "571-Horde-103484"),
        new Region(571U, WoWFactionGroup.Horde, 252.616f, -4800.61f, 577.761f, -4411.29f, "571-Horde-103487"),
        new Region(571U, WoWFactionGroup.Horde, 3665.5f, 1386.95f, 3982.94f, 1813.65f, "571-Horde-105361"),
        new Region(571U, WoWFactionGroup.Horde, 3062.14f, -904.924f, 3379.85f, -531.484f, "571-Horde-109733"),
        new Region(571U, WoWFactionGroup.Horde, 4371.59f, 5541.71f, 4630.51f, 5841.65f, "571-Horde-113420"),
        new Region(571U, WoWFactionGroup.Horde, 2017.47f, -3080.28f, 2227.63f, -2872.74f, "571-Horde-116970"),
        new Region(571U, WoWFactionGroup.Horde, 4828.2f, 1087.95f, 5100.3f, 1437.91f, "571-Horde-117620"),
        new Region(571U, WoWFactionGroup.Horde, 2540.94f, 5970.56f, 3225.58f, 6564.38f, "571-Horde-125566"),
    };

    internal static IEnumerable<Vector2[]> For(uint map, WoWFactionGroup actor)
    {
        if (actor == WoWFactionGroup.Neutral) yield break;
        foreach (var region in Regions)
            if (region.Map == map && region.Owner != actor)
                yield return new[] { new Vector2(region.MinX, region.MinY), new Vector2(region.MaxX, region.MinY),
                    new Vector2(region.MaxX, region.MaxY), new Vector2(region.MinX, region.MaxY) };
    }
}
